#!/usr/bin/env python3
"""
generate_notebook.py
====================
Script ini menghasilkan Jupyter Notebook lengkap:
  hyperparameter_tuning_analysis_sentiment.ipynb

Cara menjalankan script ini:
  python generate_notebook.py

Setelah notebook dibuat, jalankan di folder notebooks/:
  jupyter notebook hyperparameter_tuning_analysis_sentiment.ipynb

─── Requirement untuk script INI ───────────────────────────────
  pip install nbformat

─── Requirement untuk NOTEBOOK yang dihasilkan ─────────────────
  pip install tensorflow optuna scikit-learn pandas numpy
              matplotlib seaborn tqdm
"""

import nbformat as nbf
import os

NOTEBOOK_FILENAME = "hyperparameter_tuning_analysis_sentiment.ipynb"


# ─────────────────────────────────────────────────────────────────
# Helper: buat cell markdown / code
# ─────────────────────────────────────────────────────────────────
def md(src: str) -> nbf.NotebookNode:
    return nbf.v4.new_markdown_cell(src)


def code(src: str) -> nbf.NotebookNode:
    return nbf.v4.new_code_cell(src)


# ─────────────────────────────────────────────────────────────────
# Builder utama
# ─────────────────────────────────────────────────────────────────
def build_notebook() -> nbf.NotebookNode:
    nb = nbf.v4.new_notebook()
    nb.metadata = {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {
            "codemirror_mode": {"name": "ipython", "version": 3},
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "version": "3.9.0",
        },
    }

    cells = []

    # ══════════════════════════════════════════════════════════════
    # JUDUL NOTEBOOK
    # ══════════════════════════════════════════════════════════════
    cells.append(md(
        "# Hyperparameter Tuning untuk Analisis Sentimen Berbasis Data Teks\n"
        "### Pemodelan RNN, LSTM, dan GRU dengan TensorFlow/Keras\n\n"
        "| Informasi | Detail |\n"
        "|:----------|:-------|\n"
        "| **Mata Kuliah** | Deep Learning |\n"
        "| **Dosen Pengampu** | Ahmad Fathan Hidayatullah, Ph.D. |\n"
        "| **Dataset** | Indonesian Mobile Banking App Reviews Dataset |\n"
        "| **Sumber** | [Kaggle – reginakirana]"
        "(https://www.kaggle.com/datasets/reginakirana/"
        "indonesian-mobile-banking-app-reviews-dataset) |\n"
        "| **Framework** | TensorFlow / Keras |\n"
        "| **Metode Tuning** | Optuna (TPE – Tree-structured Parzen Estimator) |\n"
        "| **Random Seed** | 42 |\n\n"
        "---\n"
        "> **Perhatian:** Letakkan `dataset_perbankan.csv` di `../data/raw/`"
        " sebelum menjalankan notebook ini dari folder `notebooks/`."
    ))

    # ══════════════════════════════════════════════════════════════
    # BAB 1: PENDAHULUAN & IMPORT LIBRARY
    # ══════════════════════════════════════════════════════════════
    cells.append(md(
        "---\n"
        "# Bab 1: Pendahuluan & Import Library\n\n"
        "Bab ini menyiapkan seluruh pustaka yang dibutuhkan dan menetapkan "
        "**random seed global (SEED = 42)** pada Numpy, Python `random`, dan "
        "TensorFlow agar setiap eksekusi ulang menghasilkan output yang identik "
        "(*reproducibility*)."
    ))

    cells.append(code(
        "# Instalasi pustaka (jalankan sekali, lalu restart kernel jika diperlukan)\n"
        "# !pip install tensorflow optuna scikit-learn pandas numpy "
        "matplotlib seaborn tqdm\n"
    ))

    cells.append(code(
        "# ════════════════════════════════════════════════════════════\n"
        "#  IMPORT LIBRARY & KONFIGURASI GLOBAL\n"
        "# ════════════════════════════════════════════════════════════\n"
        "import os\n"
        "import re\n"
        "import random\n"
        "import warnings\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "import matplotlib.pyplot as plt\n"
        "import matplotlib.ticker as mticker\n"
        "import seaborn as sns\n"
        "from IPython.display import display\n"
        "\n"
        "warnings.filterwarnings('ignore')\n"
        "pd.options.display.float_format = '{:.4f}'.format\n"
        "\n"
        "# ── RANDOM SEED GLOBAL ───────────────────────────────────\n"
        "SEED = 42\n"
        "os.environ['PYTHONHASHSEED'] = str(SEED)\n"
        "random.seed(SEED)\n"
        "np.random.seed(SEED)\n"
        "\n"
        "import tensorflow as tf\n"
        "tf.random.set_seed(SEED)\n"
        "os.environ['TF_DETERMINISTIC_OPS'] = '1'\n"
        "os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'\n"
        "\n"
        "import logging\n"
        "os.makedirs('../logs', exist_ok=True)\n"
        "log_format = '%(asctime)s - %(name)s - %(levelname)s - %(message)s'\n"
        "# Setup logging ke file\n"
        "logging.basicConfig(filename='../logs/experiment.log', level=logging.INFO, \n"
        "                    format=log_format, filemode='w')\n"
        "logger = logging.getLogger('sentiment_experiment')\n"
        "logger.info('=== EKSPERIMEN DIMULAI ===')\n"
        "\n"
        "import optuna\n"
        "# Arahkan log optuna ke file agar console jupyter tetap rapi\n"
        "optuna_logger = logging.getLogger('optuna')\n"
        "optuna_logger.setLevel(logging.INFO)\n"
        "optuna_logger.addHandler(logging.FileHandler('../logs/optuna_study.log'))\n"
        "optuna.logging.set_verbosity(optuna.logging.WARNING)\n"
        "\n"
        "from sklearn.model_selection import train_test_split\n"
        "from sklearn.preprocessing import LabelEncoder\n"
        "from sklearn.metrics import (\n"
        "    accuracy_score, precision_score, recall_score,\n"
        "    f1_score, confusion_matrix, classification_report\n"
        ")\n"
        "from tensorflow.keras.preprocessing.text import Tokenizer\n"
        "from tensorflow.keras.preprocessing.sequence import pad_sequences\n"
        "from tensorflow.keras.models import Sequential\n"
        "from tensorflow.keras.layers import (\n"
        "    Embedding, SimpleRNN, LSTM, GRU, Dense, Dropout\n"
        ")\n"
        "from tensorflow.keras.callbacks import EarlyStopping\n"
        "from tensorflow.keras.optimizers import Adam\n"
        "\n"
        "# ── KONSTANTA EKSPERIMEN ─────────────────────────────────\n"
        "VOCAB_SIZE    = 10_000  # Ukuran kosakata maksimum\n"
        "MAX_LEN       = 100     # Panjang sekuens setelah padding\n"
        "EMBEDDING_DIM = 64      # Dimensi embedding (statis)\n"
        "MAX_EPOCHS    = 20      # Epoch maksimum per trial\n"
        "PATIENCE      = 3       # EarlyStopping patience\n"
        "N_TRIALS      = 30      # Trial Optuna per arsitektur (kurangi jika CPU terbatas)\n"
        "TEST_SIZE     = 0.15    # Proporsi data uji\n"
        "VAL_SIZE      = 0.15    # Proporsi data validasi\n"
        "ARCH_LIST     = ['RNN', 'LSTM', 'GRU']\n"
        "PALETTE       = ['#BBDEFB', '#42A5F5', '#0D47A1']\n"
        "\n"
        "print('Semua library berhasil diimport!')\n"
        "print(f'  TensorFlow : {tf.__version__}')\n"
        "print(f'  Optuna     : {optuna.__version__}')\n"
        "print(f'  SEED       : {SEED}')\n"
        "print(f'  N_TRIALS   : {N_TRIALS} per arsitektur ({N_TRIALS * 3} total)')\n"
    ))

    # ══════════════════════════════════════════════════════════════
    # BAB 2: DESKRIPSI DATASET
    # ══════════════════════════════════════════════════════════════
    cells.append(md(
        "---\n"
        "# Bab 2: Deskripsi Dataset\n\n"
        "## 2.1 Informasi Dataset\n\n"
        "| Atribut | Keterangan |\n"
        "|:--------|:-----------|\n"
        "| **Nama** | Indonesian Mobile Banking App Reviews Dataset |\n"
        "| **Sumber** | [Kaggle – reginakirana](https://www.kaggle.com/datasets/"
        "reginakirana/indonesian-mobile-banking-app-reviews-dataset) |\n"
        "| **Jumlah Data** | ± 12.000 ulasan |\n"
        "| **Kelas Sentimen** | 3 kelas: Positif, Negatif, Netral |\n"
        "| **Bahasa** | Indonesia |\n"
        "| **Deskripsi** | Dataset berisi ulasan pengguna aplikasi *mobile banking* "
        "berbahasa Indonesia dari Google Play Store yang telah dilabeli sentimen "
        "positif, negatif, dan netral. Relevan untuk menguji model NLP berbasis "
        "RNN dalam memahami konteks bahasa informal Indonesia. |\n\n"
        "## 2.2 Memuat & Mengeksplorasi Dataset\n"
    ))

    cells.append(code(
        "# ════════════════════════════════════════════════════════════\n"
        "#  2.2 MUAT DATASET\n"
        "# ════════════════════════════════════════════════════════════\n"
        "\n"
        "POSSIBLE_PATHS = [\n"
        "    '../data/raw/dataset_perbankan.csv',\n"
        "    'data/raw/dataset_perbankan.csv',\n"
        "    'dataset_perbankan.csv',\n"
        "    '../dataset_perbankan.csv',\n"
        "]\n"
        "\n"
        "df_raw = None\n"
        "for _path in POSSIBLE_PATHS:\n"
        "    if os.path.exists(_path):\n"
        "        try:\n"
        "            df_raw = pd.read_csv(_path, encoding='utf-8')\n"
        "        except UnicodeDecodeError:\n"
        "            df_raw = pd.read_csv(_path, encoding='latin-1')\n"
        "        print(f'Dataset dimuat dari : {_path}')\n"
        "        break\n"
        "\n"
        "if df_raw is None:\n"
        "    raise FileNotFoundError(\n"
        "        \"File 'dataset_perbankan.csv' tidak ditemukan!\\n\"\n"
        "        \"Letakkan file di salah satu path berikut:\\n\"\n"
        "        + \"\\n\".join(f\"  - {p}\" for p in POSSIBLE_PATHS)\n"
        "    )\n"
        "\n"
        "print(f'Shape dataset : {df_raw.shape}  '\n"
        "      f'({df_raw.shape[0]:,} baris x {df_raw.shape[1]} kolom)')\n"
        "print(f'Kolom         : {df_raw.columns.tolist()}')\n"
    ))

    cells.append(code(
        "# ── Deteksi Kolom Teks & Label Otomatis ─────────────────────\n"
        "_TEXT_CANDS  = ['review','text','content','ulasan','komentar',\n"
        "                'Review','Text','Content','Ulasan','comment']\n"
        "_LABEL_CANDS = ['sentiment','label','sentimen','Sentiment',\n"
        "                'Label','class','Class','score','kategori']\n"
        "\n"
        "TEXT_COL  = next((c for c in _TEXT_CANDS  if c in df_raw.columns), None)\n"
        "LABEL_COL = next((c for c in _LABEL_CANDS if c in df_raw.columns), None)\n"
        "\n"
        "if TEXT_COL is None:\n"
        "    TEXT_COL = df_raw.columns[0]\n"
        "    print(f'Kolom teks tidak terdeteksi, pakai kolom pertama: {TEXT_COL}')\n"
        "if LABEL_COL is None:\n"
        "    LABEL_COL = df_raw.columns[-1]\n"
        "    print(f'Kolom label tidak terdeteksi, pakai kolom terakhir: {LABEL_COL}')\n"
        "\n"
        "print(f'Kolom Teks  : \"{TEXT_COL}\"')\n"
        "print(f'Kolom Label : \"{LABEL_COL}\"')\n"
        "\n"
        "df = df_raw[[TEXT_COL, LABEL_COL]].copy()\n"
        "df.columns = ['text', 'label']\n"
        "df['label'] = df['label'].astype(str).str.strip()\n"
        "\n"
        "# Drop baris dengan nilai null\n"
        "df.dropna(subset=['text', 'label'], inplace=True)\n"
        "df.reset_index(drop=True, inplace=True)\n"
        "\n"
        "print(f'\\nJumlah data valid : {len(df):,}')\n"
        "print('\\n5 Contoh Data:')\n"
        "display(df.head())\n"
    ))

    cells.append(code(
        "# ── Info & Missing Values ────────────────────────────────────\n"
        "print('=== INFO DATASET ===')\n"
        "df.info()\n"
        "print('\\n=== MISSING VALUES ===')\n"
        "print(df.isnull().sum())\n"
    ))

    cells.append(code(
        "# ════════════════════════════════════════════════════════════\n"
        "#  2.3 DISTRIBUSI LABEL SENTIMEN\n"
        "# ════════════════════════════════════════════════════════════\n"
        "\n"
        "label_counts = df['label'].value_counts()\n"
        "label_pct    = df['label'].value_counts(normalize=True) * 100\n"
        "\n"
        "dist_df = pd.DataFrame({\n"
        "    'Kelas'           : label_counts.index,\n"
        "    'Jumlah'          : label_counts.values,\n"
        "    'Persentase (%)' : label_pct.values.round(2)\n"
        "}).reset_index(drop=True)\n"
        "dist_df.index += 1\n"
        "print('=== DISTRIBUSI LABEL SENTIMEN ===')\n"
        "display(dist_df)\n"
        "\n"
        "# ── Visualisasi Bar + Pie ─────────────────────────────────────\n"
        "fig, axes = plt.subplots(1, 2, figsize=(13, 5))\n"
        "fig.suptitle('Distribusi Label Sentimen – Mobile Banking App Reviews',\n"
        "             fontsize=13, fontweight='bold')\n"
        "\n"
        "_colors = ['#4CAF50', '#F44336', '#2196F3', '#FF9800', '#9C27B0']\n"
        "import matplotlib.cm as cm\n"
        "import matplotlib.colors as mcolors\n"
        "\n"
        "norm_c = mcolors.Normalize(vmin=0, vmax=max(label_counts.values))\n"
        "color_map = {lbl: cm.Blues(norm_c(val)) for lbl, val in zip(label_counts.index, label_counts.values)}\n"
        "_colors = [color_map[lbl] for lbl in label_counts.index]\n"
        "\n"
        "axes[0].bar(label_counts.index, label_counts.values,\n"
        "            color=_colors,\n"
        "            edgecolor='black', linewidth=0.7)\n"
        "axes[0].set_title('Jumlah Data per Kelas')\n"
        "axes[0].set_xlabel('Kelas Sentimen')\n"
        "axes[0].set_ylabel('Jumlah Data')\n"
        "axes[0].grid(axis='y', alpha=0.3)\n"
        "for i, (_, val) in enumerate(zip(label_counts.index, label_counts.values)):\n"
        "    axes[0].text(i, val + max(label_counts) * 0.01,\n"
        "                 f'{val:,}', ha='center', fontweight='bold')\n"
        "\n"
        "axes[1].pie(label_counts.values, labels=label_counts.index,\n"
        "            colors=_colors[:len(label_counts)],\n"
        "            autopct='%1.1f%%', startangle=140, pctdistance=0.8,\n"
        "            wedgeprops={'edgecolor': 'white', 'linewidth': 1.5})\n"
        "axes[1].set_title('Proporsi Kelas Sentimen')\n"
        "\n"
        "plt.tight_layout()\n"
        "os.makedirs('../images/output', exist_ok=True)\n"
        "plt.savefig('../images/output/distribusi_label.png', dpi=150, bbox_inches='tight')\n"
        "plt.show()\n"
        "print(\"Gambar disimpan -> '../images/output/distribusi_label.png'\")\n"
    ))

    # ── EDA 2.4: Distribusi Panjang Teks ──────────────────────────
    cells.append(md(
        "## 2.4 Exploratory Data Analysis (EDA)\n\n"
        "Analisis eksplorasi untuk memahami karakteristik data teks secara lebih mendalam "
        "sebelum masuk ke tahap preprocessing.\n"
    ))

    cells.append(code(
        "# ════════════════════════════════════════════════════════════\n"
        "#  2.4a DISTRIBUSI PANJANG TEKS (JUMLAH KATA)\n"
        "# ════════════════════════════════════════════════════════════\n"
        "\n"
        "df['word_count'] = df['text'].apply(lambda x: len(str(x).split()))\n"
        "df['char_count'] = df['text'].apply(lambda x: len(str(x)))\n"
        "\n"
        "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n"
        "fig.suptitle('Distribusi Panjang Teks Ulasan', fontsize=13, fontweight='bold')\n"
        "\n"
        "# Histogram jumlah kata\n"
        "for lbl in (CLASS_NAMES if 'CLASS_NAMES' in dir() else df['label'].unique()):\n"
        "    subset = df[df['label'] == lbl]['word_count']\n"
        "    axes[0].hist(subset, bins=50, alpha=0.6, label=lbl, color=color_map.get(lbl, 'blue'), edgecolor='white')\n"
        "axes[0].set_title('Distribusi Jumlah Kata per Ulasan')\n"
        "axes[0].set_xlabel('Jumlah Kata')\n"
        "axes[0].set_ylabel('Frekuensi')\n"
        "axes[0].legend()\n"
        "axes[0].grid(axis='y', alpha=0.3)\n"
        "\n"
        "# Boxplot jumlah kata per label\n"
        "labels_unique = df['label'].unique().tolist()\n"
        "box_data = [df[df['label'] == lbl]['word_count'].values for lbl in labels_unique]\n"
        "bp = axes[1].boxplot(box_data, patch_artist=True,\n"
        "                     showmeans=True, showfliers=True)\n"
        "axes[1].set_xticks(range(1, len(labels_unique) + 1))\n"
        "axes[1].set_xticklabels(labels_unique)\n"
        "for patch, lbl in zip(bp['boxes'], labels_unique):\n"
        "    patch.set_facecolor(color_map.get(lbl, 'blue'))\n"
        "    patch.set_alpha(0.6)\n"
        "axes[1].set_title('Boxplot Jumlah Kata per Kelas Sentimen')\n"
        "axes[1].set_xlabel('Kelas Sentimen')\n"
        "axes[1].set_ylabel('Jumlah Kata')\n"
        "axes[1].grid(axis='y', alpha=0.3)\n"
        "\n"
        "plt.tight_layout()\n"
        "plt.savefig('../images/output/eda_distribusi_panjang_teks.png',\n"
        "            dpi=150, bbox_inches='tight')\n"
        "plt.show()\n"
        "\n"
        "# Statistik deskriptif panjang teks\n"
        "print('=== STATISTIK PANJANG TEKS (JUMLAH KATA) PER KELAS ===')\n"
        "display(df.groupby('label')['word_count'].describe().round(2))\n"
        "print(f\"\\nGambar disimpan -> '../images/output/eda_distribusi_panjang_teks.png'\")\n"
    ))

    cells.append(code(
        "# ════════════════════════════════════════════════════════════\n"
        "#  2.4b TOP 20 KATA PALING SERING MUNCUL PER KELAS\n"
        "# ════════════════════════════════════════════════════════════\n"
        "\n"
        "from collections import Counter\n"
        "\n"
        "fig, axes = plt.subplots(1, len(df['label'].unique()),\n"
        "                         figsize=(7 * len(df['label'].unique()), 6))\n"
        "if len(df['label'].unique()) == 1:\n"
        "    axes = [axes]\n"
        "\n"
        "fig.suptitle('Top 20 Kata Paling Sering Muncul per Kelas Sentimen',\n"
        "             fontsize=14, fontweight='bold')\n"
        "\n"
        "for ax, lbl in zip(axes, sorted(df['label'].unique())):\n"
        "    all_words = ' '.join(df[df['label'] == lbl]['text'].astype(str).str.lower()).split()\n"
        "    # Filter stopwords sederhana bahasa Indonesia\n"
        "    stop_id = {'yang','dan','di','ini','itu','dengan','untuk','tidak','dari',\n"
        "              'ke','ada','pada','juga','sudah','saya','bisa','atau','akan',\n"
        "              'ya','lagi','sangat','sekali','tapi','karena','kalau','aja',\n"
        "              'nya','yg','gak','ga','nih','dong','deh','sih','the','is','a',\n"
        "              'to','and','of','in','for','it','this','was','my','app','aplikasi'}\n"
        "    filtered = [w for w in all_words if w not in stop_id and len(w) > 2]\n"
        "    top20 = Counter(filtered).most_common(20)\n"
        "    words, counts = zip(*top20) if top20 else ([], [])\n"
        "    norm_w = mcolors.Normalize(vmin=0, vmax=max(counts))\n"
        "    bar_colors = [cm.Blues(norm_w(c)) for c in list(reversed(counts))]\n"
        "    ax.barh(list(reversed(words)), list(reversed(counts)),\n"
        "            color=bar_colors, edgecolor='black', linewidth=0.5, alpha=0.8)\n"
        "    ax.set_title(f'Sentimen: {lbl.upper()}', fontsize=12, fontweight='bold')\n"
        "    ax.set_xlabel('Frekuensi')\n"
        "    ax.grid(axis='x', alpha=0.3)\n"
        "\n"
        "plt.tight_layout()\n"
        "plt.savefig('../images/output/eda_top_words_per_kelas.png',\n"
        "            dpi=150, bbox_inches='tight')\n"
        "plt.show()\n"
        "print(\"Gambar disimpan -> '../images/output/eda_top_words_per_kelas.png'\")\n"
    ))

    cells.append(code(
        "# ════════════════════════════════════════════════════════════\n"
        "#  2.4c DISTRIBUSI RATING (SCORE) PER KELAS SENTIMEN\n"
        "# ════════════════════════════════════════════════════════════\n"
        "\n"
        "if 'score' in df_raw.columns:\n"
        "    _score_col = 'score'\n"
        "elif 'Score' in df_raw.columns:\n"
        "    _score_col = 'Score'\n"
        "elif 'rating' in df_raw.columns:\n"
        "    _score_col = 'rating'\n"
        "else:\n"
        "    _score_col = None\n"
        "\n"
        "if _score_col is not None:\n"
        "    df['score'] = df_raw.loc[df.index, _score_col].values\n"
        "    fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n"
        "    fig.suptitle('Distribusi Rating (Score) vs Label Sentimen',\n"
        "                 fontsize=13, fontweight='bold')\n"
        "\n"
        "    # Countplot rating per sentimen\n"
        "    score_label_ct = df.groupby(['score', 'label']).size().unstack(fill_value=0)\n"
        "    score_label_ct.plot(kind='bar', ax=axes[0],\n"
        "                       color=[color_map.get(c, 'blue') for c in score_label_ct.columns],\n"
        "                       edgecolor='black', linewidth=0.5)\n"
        "    axes[0].set_title('Jumlah Ulasan per Rating & Sentimen')\n"
        "    axes[0].set_xlabel('Rating (Score)')\n"
        "    axes[0].set_ylabel('Jumlah')\n"
        "    axes[0].legend(title='Sentimen')\n"
        "    axes[0].grid(axis='y', alpha=0.3)\n"
        "    axes[0].tick_params(axis='x', rotation=0)\n"
        "\n"
        "    # Heatmap rating vs sentimen\n"
        "    ct_matrix = pd.crosstab(df['score'], df['label'])\n"
        "    sns.heatmap(ct_matrix, annot=True, fmt='d', cmap='Blues',\n"
        "                ax=axes[1], linewidths=0.5, cbar_kws={'label': 'Jumlah'})\n"
        "    axes[1].set_title('Heatmap: Rating vs Sentimen')\n"
        "    axes[1].set_xlabel('Label Sentimen')\n"
        "    axes[1].set_ylabel('Rating (Score)')\n"
        "\n"
        "    plt.tight_layout()\n"
        "    plt.savefig('../images/output/eda_rating_vs_sentimen.png',\n"
        "                dpi=150, bbox_inches='tight')\n"
        "    plt.show()\n"
        "    print(\"Gambar disimpan -> '../images/output/eda_rating_vs_sentimen.png'\")\n"
        "else:\n"
        "    print('Kolom score/rating tidak ditemukan di dataset, skip visualisasi ini.')\n"
    ))

    cells.append(code(
        "# ════════════════════════════════════════════════════════════\n"
        "#  2.4d DISTRIBUSI APLIKASI MOBILE BANKING\n"
        "# ════════════════════════════════════════════════════════════\n"
        "\n"
        "if 'app_name' in df_raw.columns:\n"
        "    app_counts = df_raw['app_name'].value_counts()\n"
        "    fig, ax = plt.subplots(figsize=(10, 5))\n"
        "    norm_a = mcolors.Normalize(vmin=0, vmax=max(app_counts.values))\n"
        "    bar_colors = [cm.Blues(norm_a(c)) for c in app_counts.values[::-1]]\n"
        "    ax.barh(app_counts.index[::-1], app_counts.values[::-1],\n"
        "            color=bar_colors,\n"
        "            edgecolor='black', linewidth=0.5)\n"
        "    for i, (name, val) in enumerate(zip(app_counts.index[::-1],\n"
        "                                         app_counts.values[::-1])):\n"
        "        ax.text(val + max(app_counts) * 0.01, i,\n"
        "                f'{val:,}', va='center', fontweight='bold', fontsize=9)\n"
        "    ax.set_title('Distribusi Ulasan per Aplikasi Mobile Banking',\n"
        "                fontsize=13, fontweight='bold')\n"
        "    ax.set_xlabel('Jumlah Ulasan')\n"
        "    ax.grid(axis='x', alpha=0.3)\n"
        "    plt.tight_layout()\n"
        "    plt.savefig('../images/output/eda_distribusi_app.png',\n"
        "                dpi=150, bbox_inches='tight')\n"
        "    plt.show()\n"
        "    print(f'Jumlah aplikasi unik: {len(app_counts)}')\n"
        "    display(app_counts.reset_index().rename(\n"
        "        columns={'index': 'Aplikasi', 'app_name': 'Jumlah Ulasan'}))\n"
        "    print(\"Gambar disimpan -> '../images/output/eda_distribusi_app.png'\")\n"
        "else:\n"
        "    print('Kolom app_name tidak ditemukan di dataset, skip visualisasi ini.')\n"
    ))

    # ══════════════════════════════════════════════════════════════
    # BAB 3: PREPROCESSING DATA
    # ══════════════════════════════════════════════════════════════
    cells.append(md(
        "---\n"
        "# Bab 3: Preprocessing Data\n\n"
        "| Langkah | Teknik | Keterangan |\n"
        "|:--------|:-------|:-----------|\n"
        "| **3.1 Text Cleansing** | Regex | Lowercase · hapus URL · "
        "karakter non-alfabet · normalisasi spasi |\n"
        "| **3.2 Label Encoding** | `LabelEncoder` | String label → Integer (0, 1, 2) |\n"
        "| **3.3 Tokenisasi** | `Keras Tokenizer` | Fit **hanya** pada data latih "
        "(mencegah *data leakage*) |\n"
        "| **3.4 Padding** | `pad_sequences` | Seragamkan panjang → `MAX_LEN=100` |\n"
        "| **3.5 Split** | `train_test_split` stratified | "
        "70% Train · 15% Val · 15% Test |\n"
    ))

    cells.append(code(
        "# ════════════════════════════════════════════════════════════\n"
        "#  3.1 TEXT CLEANSING\n"
        "# ════════════════════════════════════════════════════════════\n"
        "\n"
        "def clean_text(text: str) -> str:\n"
        "    \"\"\"Membersihkan teks ulasan bahasa Indonesia untuk NLP.\"\"\"\n"
        "    text = str(text).lower()\n"
        "    text = re.sub(r'http\\S+|www\\S+|https\\S+', '', text)  # hapus URL\n"
        "    text = re.sub(r'@\\w+|#\\w+', '', text)                 # hapus mention/hashtag\n"
        "    text = re.sub(r'[^a-z\\s]', ' ', text)                  # hanya huruf & spasi\n"
        "    text = re.sub(r'\\s+', ' ', text).strip()               # hapus spasi berlebih\n"
        "    return text\n"
        "\n"
        "df['text_clean'] = df['text'].apply(clean_text)\n"
        "\n"
        "n_before = len(df)\n"
        "df = df[df['text_clean'].str.len() > 2].reset_index(drop=True)\n"
        "n_after  = len(df)\n"
        "\n"
        "print(f'Text cleansing selesai.')\n"
        "print(f'  Sebelum : {n_before:,} baris')\n"
        "print(f'  Sesudah : {n_after:,} baris  ({n_before - n_after} baris dihapus)')\n"
        "print('\\n3 Contoh Sebelum & Sesudah Cleansing:')\n"
        "for idx in df.sample(3, random_state=SEED).index:\n"
        "    print(f'\\n  [SEBELUM] {df.at[idx, \"text\"][:120]}')\n"
        "    print(f'  [SESUDAH] {df.at[idx, \"text_clean\"][:120]}')\n"
    ))

    cells.append(code(
        "# ════════════════════════════════════════════════════════════\n"
        "#  3.2 LABEL ENCODING\n"
        "# ════════════════════════════════════════════════════════════\n"
        "\n"
        "le = LabelEncoder()\n"
        "df['label_enc'] = le.fit_transform(df['label'])\n"
        "\n"
        "NUM_CLASSES = len(le.classes_)\n"
        "CLASS_NAMES = list(le.classes_)\n"
        "\n"
        "print(f'Label encoding selesai.')\n"
        "print(f'  Kelas asal   : {CLASS_NAMES}')\n"
        "print(f'  Kode numerik : {list(range(NUM_CLASSES))}')\n"
        "print(f'  Jumlah kelas : {NUM_CLASSES}')\n"
        "\n"
        "display(pd.DataFrame({'Label Asli': CLASS_NAMES,\n"
        "                      'Kode Numerik': list(range(NUM_CLASSES))}))\n"
    ))

    cells.append(code(
        "# ════════════════════════════════════════════════════════════\n"
        "#  3.3-3.5 TOKENISASI, PADDING & SPLIT DATA\n"
        "# ════════════════════════════════════════════════════════════\n"
        "\n"
        "X = df['text_clean'].values\n"
        "y = df['label_enc'].values\n"
        "\n"
        "# Langkah 1: pisahkan Test (15%) dari sisa data\n"
        "X_temp, X_test, y_temp, y_test = train_test_split(\n"
        "    X, y, test_size=TEST_SIZE, random_state=SEED, stratify=y\n"
        ")\n"
        "\n"
        "# Langkah 2: dari sisa 85%, pisahkan Val agar total Val ~15%\n"
        "_val_ratio = VAL_SIZE / (1.0 - TEST_SIZE)  # 0.15/0.85 ~= 0.1765\n"
        "X_train, X_val, y_train, y_val = train_test_split(\n"
        "    X_temp, y_temp,\n"
        "    test_size=_val_ratio,\n"
        "    random_state=SEED,\n"
        "    stratify=y_temp\n"
        ")\n"
        "\n"
        "print('Pembagian data (Stratified Split):')\n"
        "print(f'  Train : {len(X_train):>6,}  ({len(X_train)/len(X)*100:.1f}%)')\n"
        "print(f'  Val   : {len(X_val):>6,}  ({len(X_val)/len(X)*100:.1f}%)')\n"
        "print(f'  Test  : {len(X_test):>6,}  ({len(X_test)/len(X)*100:.1f}%)')\n"
        "print(f'  Total : {len(X):>6,}')\n"
        "\n"
        "# ── Tokenizer: fit HANYA pada data Train (cegah data leakage)\n"
        "tokenizer = Tokenizer(num_words=VOCAB_SIZE, oov_token='<OOV>')\n"
        "tokenizer.fit_on_texts(X_train)\n"
        "\n"
        "print(f'\\nTokenizer selesai.')\n"
        "print(f'  Kosakata unik ditemukan : {len(tokenizer.word_index):,}')\n"
        "print(f'  Vocab yang digunakan    : {min(len(tokenizer.word_index)+1, VOCAB_SIZE+1):,}')\n"
        "\n"
        "# ── Konversi teks -> sekuens integer -> padding ──────────────\n"
        "def to_padded(texts):\n"
        "    seqs = tokenizer.texts_to_sequences(texts)\n"
        "    return pad_sequences(seqs, maxlen=MAX_LEN, padding='post', truncating='post')\n"
        "\n"
        "X_train_seq = to_padded(X_train)\n"
        "X_val_seq   = to_padded(X_val)\n"
        "X_test_seq  = to_padded(X_test)\n"
        "\n"
        "print(f'\\nPadding selesai (MAX_LEN={MAX_LEN}):')\n"
        "print(f'  X_train_seq : {X_train_seq.shape}')\n"
        "print(f'  X_val_seq   : {X_val_seq.shape}')\n"
        "print(f'  X_test_seq  : {X_test_seq.shape}')\n"
    ))

    # ══════════════════════════════════════════════════════════════
    # BAB 4: ARSITEKTUR MODEL
    # ══════════════════════════════════════════════════════════════
    cells.append(md(
        "---\n"
        "# Bab 4: Arsitektur Model\n\n"
        "## 4.1 Desain Arsitektur\n\n"
        "Tiga arsitektur diuji dengan **struktur yang identik** agar perbandingan adil:\n\n"
        "```\n"
        "Input (sekuens integer, panjang MAX_LEN=100)\n"
        "  └─ Embedding  [VOCAB_SIZE x EMBEDDING_DIM=64]  <- STATIS\n"
        "      └─ RNN / LSTM / GRU  [units]              <- hyperparameter\n"
        "          └─ Dropout  [rate]                    <- hyperparameter\n"
        "              └─ Dense Softmax  [num_classes]\n"
        "```\n\n"
        "## 4.2 Parameter Statis vs Hyperparameter\n\n"
        "| Jenis | Parameter | Nilai |\n"
        "|:------|:----------|:------|\n"
        "| **Statis** | Jumlah layer rekuren | 1 |\n"
        "| **Statis** | Dimensi embedding | 64 |\n"
        "| **Statis** | Optimizer | Adam |\n"
        "| **Statis** | Loss | Sparse Categorical Crossentropy |\n"
        "| **Statis** | Max epoch | 20 + EarlyStopping |\n"
        "| **Hyperparameter** | Learning rate | [1e-4, 1e-2] log-uniform |\n"
        "| **Hyperparameter** | Batch size | {16, 32, 64} |\n"
        "| **Hyperparameter** | Hidden units | {32, 64, 128} |\n"
        "| **Hyperparameter** | Dropout rate | [0.1, 0.5] uniform |\n"
    ))

    cells.append(code(
        "# ════════════════════════════════════════════════════════════\n"
        "#  4.3 FUNGSI PEMBANGUN MODEL\n"
        "# ════════════════════════════════════════════════════════════\n"
        "\n"
        "ARCH_LAYER_MAP = {\n"
        "    'RNN' : SimpleRNN,\n"
        "    'LSTM': LSTM,\n"
        "    'GRU' : GRU,\n"
        "}\n"
        "\n"
        "def build_model(model_type: str,\n"
        "                units: int,\n"
        "                dropout_rate: float,\n"
        "                learning_rate: float) -> tf.keras.Model:\n"
        "    \"\"\"\n"
        "    Membangun model Sequential dengan satu layer rekuren.\n"
        "\n"
        "    Parameters\n"
        "    ----------\n"
        "    model_type    : 'RNN', 'LSTM', atau 'GRU'\n"
        "    units         : Jumlah hidden units [hyperparameter]\n"
        "    dropout_rate  : Tingkat dropout [hyperparameter]\n"
        "    learning_rate : Learning rate Adam [hyperparameter]\n"
        "    \"\"\"\n"
        "    if model_type not in ARCH_LAYER_MAP:\n"
        "        raise ValueError(f'model_type harus salah satu dari '\n"
        "                         f'{list(ARCH_LAYER_MAP.keys())}')\n"
        "    RecLayer = ARCH_LAYER_MAP[model_type]\n"
        "\n"
        "    model = Sequential([\n"
        "        Embedding(input_dim=VOCAB_SIZE + 1,\n"
        "                  output_dim=EMBEDDING_DIM,\n"
        "                  input_length=MAX_LEN,\n"
        "                  name='embedding'),\n"
        "        RecLayer(units, name=f'{model_type.lower()}_layer'),\n"
        "        Dropout(dropout_rate, name='dropout'),\n"
        "        Dense(NUM_CLASSES, activation='softmax', name='output'),\n"
        "    ], name=f'Model_{model_type}')\n"
        "\n"
        "    model.compile(\n"
        "        optimizer=Adam(learning_rate=learning_rate),\n"
        "        loss='sparse_categorical_crossentropy',\n"
        "        metrics=['accuracy']\n"
        "    )\n"
        "    return model\n"
        "\n"
        "# ── Tampilkan ringkasan contoh LSTM ──────────────────────────\n"
        "print('=== Contoh Arsitektur: LSTM (units=64, dropout=0.3, lr=1e-3) ===')\n"
        "_demo = build_model('LSTM', 64, 0.3, 1e-3)\n"
        "_demo.summary()\n"
        "del _demo\n"
        "tf.keras.backend.clear_session()\n"
    ))

    # ══════════════════════════════════════════════════════════════
    # BAB 5: SKENARIO HYPERPARAMETER TUNING
    # ══════════════════════════════════════════════════════════════
    cells.append(md(
        "---\n"
        "# Bab 5: Skenario Hyperparameter Tuning\n\n"
        "## 5.1 Metode: Optuna dengan TPE\n\n"
        "**Optuna** dengan algoritma **TPE (Tree-structured Parzen Estimator)** "
        "adalah metode Bayesian Optimization yang secara adaptif mengeksplorasi "
        "ruang pencarian berdasarkan hasil trial sebelumnya, jauh lebih efisien "
        "daripada Grid Search maupun Random Search.\n\n"
        "## 5.2 Ruang Pencarian Hyperparameter\n\n"
        "| # | Hyperparameter | Tipe | Rentang / Pilihan | Alasan |\n"
        "|:-:|:--------------|:-----|:-----------------|:-------|\n"
        "| 1 | **Learning Rate** | Log-uniform | [1e-4, 1e-2] | "
        "Skala log agar eksplorasi merata; rentang standar Adam untuk NLP |\n"
        "| 2 | **Batch Size** | Kategoris | {16, 32, 64} | "
        "Batch kecil → gradien berisik (generalisasi baik); "
        "batch besar → training stabil |\n"
        "| 3 | **Hidden Units** | Kategoris | {32, 64, 128} | "
        "Menguji kapasitas model dari sederhana hingga kompleks |\n"
        "| 4 | **Dropout Rate** | Uniform | [0.1, 0.5] | "
        "Regularisasi standar NLP; mencegah overfitting |\n\n"
        "## 5.3 Protokol Eksperimen\n\n"
        "| Aspek | Konfigurasi |\n"
        "|:------|:------------|\n"
        "| **Data untuk evaluasi tuning** | `X_val` / `y_val` "
        "(data uji **tersembunyi**) |\n"
        "| **Metrik optimasi** | Macro F1-Score (adil untuk kelas tidak seimbang) |\n"
        "| **Trial budget** | 30 trial per arsitektur (90 total) |\n"
        "| **Sampler** | `TPESampler(seed=42)` |\n"
        "| **Early Stopping** | patience=3, monitor `val_loss` |\n"
        "| **Reproduksibilitas** | SEED=42 + seed per trial |\n"
    ))

    cells.append(code(
        "# ════════════════════════════════════════════════════════════\n"
        "#  5.4 FUNGSI OBJEKTIF OPTUNA\n"
        "# ════════════════════════════════════════════════════════════\n"
        "\n"
        "def make_objective(model_type: str):\n"
        "    \"\"\"\n"
        "    Factory function: mengembalikan fungsi objektif Optuna\n"
        "    untuk arsitektur model tertentu.\n"
        "\n"
        "    Alur:\n"
        "      trial saran HP -> bangun model -> latih pada Train\n"
        "      -> prediksi pada Val -> kembalikan Macro F1 untuk dimaksimalkan\n"
        "    \"\"\"\n"
        "    def objective(trial: optuna.Trial) -> float:\n"
        "        tf.keras.backend.clear_session()\n"
        "        tf.random.set_seed(SEED + trial.number)\n"
        "\n"
        "        # ── Sarankan hyperparameter ──────────────────────\n"
        "        lr           = trial.suggest_float(\n"
        "            'learning_rate', 1e-4, 1e-2, log=True)\n"
        "        batch_size   = trial.suggest_categorical(\n"
        "            'batch_size', [16, 32, 64])\n"
        "        units        = trial.suggest_categorical(\n"
        "            'hidden_units', [32, 64, 128])\n"
        "        dropout_rate = trial.suggest_float(\n"
        "            'dropout_rate', 0.1, 0.5)\n"
        "\n"
        "        # ── Bangun & latih model ─────────────────────────\n"
        "        model = build_model(model_type, units, dropout_rate, lr)\n"
        "\n"
        "        early_stop = EarlyStopping(\n"
        "            monitor='val_loss',\n"
        "            patience=PATIENCE,\n"
        "            restore_best_weights=True,\n"
        "            verbose=0\n"
        "        )\n"
        "        model.fit(\n"
        "            X_train_seq, y_train,\n"
        "            validation_data=(X_val_seq, y_val),\n"
        "            epochs=MAX_EPOCHS,\n"
        "            batch_size=batch_size,\n"
        "            callbacks=[early_stop],\n"
        "            verbose=0\n"
        "        )\n"
        "\n"
        "        # ── Evaluasi di data VALIDASI (bukan test!) ──────\n"
        "        y_pred = np.argmax(\n"
        "            model.predict(X_val_seq, verbose=0), axis=1)\n"
        "\n"
        "        acc  = float(accuracy_score(y_val, y_pred))\n"
        "        prec = float(precision_score(\n"
        "            y_val, y_pred, average='macro', zero_division=0))\n"
        "        rec  = float(recall_score(\n"
        "            y_val, y_pred, average='macro', zero_division=0))\n"
        "        f1   = float(f1_score(\n"
        "            y_val, y_pred, average='macro', zero_division=0))\n"
        "\n"
        "        # Simpan semua metrik sebagai atribut trial\n"
        "        trial.set_user_attr('accuracy',   round(acc,  4))\n"
        "        trial.set_user_attr('precision',  round(prec, 4))\n"
        "        trial.set_user_attr('recall',     round(rec,  4))\n"
        "        trial.set_user_attr('f1_score',   round(f1,   4))\n"
        "        trial.set_user_attr('model_type', model_type)\n"
        "\n"
        "        return f1  # Optuna akan memaksimalkan nilai ini\n"
        "\n"
        "    return objective\n"
    ))

    cells.append(code(
        "# ════════════════════════════════════════════════════════════\n"
        "#  5.5 JALANKAN OPTUNA UNTUK SEMUA ARSITEKTUR\n"
        "#  Estimasi waktu: 45-120 menit (CPU) | 15-30 menit (GPU)\n"
        "#  Kurangi N_TRIALS di Bab 1 jika waktu komputasi terbatas\n"
        "# ════════════════════════════════════════════════════════════\n"
        "\n"
        "studies = {}\n"
        "\n"
        "for arch in ARCH_LIST:\n"
        "    print(f'\\n{\"=\"*65}')\n"
        "    print(f'  Menjalankan Optuna: {arch}  |  {N_TRIALS} trials')\n"
        "    print(f'{\"=\"*65}')\n"
        "\n"
        "    study = optuna.create_study(\n"
        "        direction='maximize',\n"
        "        sampler=optuna.samplers.TPESampler(seed=SEED),\n"
        "        study_name=f'study_{arch}'\n"
        "    )\n"
        "    study.optimize(\n"
        "        make_objective(arch),\n"
        "        n_trials=N_TRIALS,\n"
        "        show_progress_bar=True\n"
        "    )\n"
        "    studies[arch] = study\n"
        "\n"
        "    best = study.best_trial\n"
        "    print(f'\\n  [{arch}] Selesai!')\n"
        "    print(f'    Best Trial # : {best.number}')\n"
        "    print(f'    Best Val F1  : {best.value:.4f}')\n"
        "    print(f'    Best Params  :')\n"
        "    for k, v in best.params.items():\n"
        "        _v = f'{v:.6f}' if isinstance(v, float) else str(v)\n"
        "        print(f'      {k:<22}: {_v}')\n"
        "\n"
        "print('\\n\\nSemua arsitektur selesai dituning!')\n"
    ))

    cells.append(code(
        "# ════════════════════════════════════════════════════════════\n"
        "#  5.6 RINGKASAN BEST PARAMS PER ARSITEKTUR\n"
        "# ════════════════════════════════════════════════════════════\n"
        "\n"
        "_summary = []\n"
        "for arch in ARCH_LIST:\n"
        "    best = studies[arch].best_trial\n"
        "    _summary.append({\n"
        "        'Arsitektur'     : arch,\n"
        "        'Trial #'        : best.number,\n"
        "        'Learning Rate'  : round(best.params['learning_rate'], 6),\n"
        "        'Batch Size'     : best.params['batch_size'],\n"
        "        'Hidden Units'   : best.params['hidden_units'],\n"
        "        'Dropout Rate'   : round(best.params['dropout_rate'], 4),\n"
        "        'Val F1 (Macro)' : round(best.value, 4),\n"
        "    })\n"
        "\n"
        "print('=== RINGKASAN BEST HYPERPARAMETER PER ARSITEKTUR ===')\n"
        "display(pd.DataFrame(_summary))\n"
    ))

    # ══════════════════════════════════════════════════════════════
    # BAB 6: HASIL EVALUASI
    # ══════════════════════════════════════════════════════════════
    cells.append(md(
        "---\n"
        "# Bab 6: Hasil Evaluasi\n\n"
        "## 6.1 Tabel 2 – Rangkuman Hasil Eksperimen (Semua Trial)\n\n"
        "Tabel berikut merangkum seluruh kombinasi hyperparameter yang diuji "
        "beserta metrik evaluasi pada **data validasi** "
        "(sesuai format Tabel 2 lembar tugas dosen).\n\n"
        "> Pemilihan HP dilakukan berdasarkan data validasi. "
        "**Data uji tidak disentuh pada tahap ini.**\n"
    ))

    cells.append(code(
        "# ════════════════════════════════════════════════════════════\n"
        "#  6.1 GENERATE TABEL 2 (Format Tugas)\n"
        "# ════════════════════════════════════════════════════════════\n"
        "\n"
        "def build_results_table(studies: dict) -> pd.DataFrame:\n"
        "    \"\"\"Kumpulkan semua trial ke dalam satu DataFrame (Tabel 2).\"\"\"\n"
        "    rows, no = [], 1\n"
        "    for arch in ARCH_LIST:\n"
        "        for trial in studies[arch].trials:\n"
        "            if trial.state == optuna.trial.TrialState.COMPLETE:\n"
        "                rows.append({\n"
        "                    'No'           : no,\n"
        "                    'Model'        : arch,\n"
        "                    'Learning Rate': round(\n"
        "                        trial.params.get('learning_rate', 0), 6),\n"
        "                    'Batch Size'   : trial.params.get('batch_size', '-'),\n"
        "                    'Hidden Units' : trial.params.get('hidden_units', '-'),\n"
        "                    'Dropout Rate' : round(\n"
        "                        trial.params.get('dropout_rate', 0), 4),\n"
        "                    'Accuracy'     : trial.user_attrs.get('accuracy', '-'),\n"
        "                    'Precision'    : trial.user_attrs.get('precision', '-'),\n"
        "                    'Recall'       : trial.user_attrs.get('recall', '-'),\n"
        "                    'F1-Score'     : trial.user_attrs.get('f1_score', '-'),\n"
        "                })\n"
        "                no += 1\n"
        "    return pd.DataFrame(rows)\n"
        "\n"
        "results_all_df = build_results_table(studies)\n"
        "\n"
        "# Tampilkan sesuai format Tabel 2\n"
        "tabel2 = results_all_df[[\n"
        "    'No', 'Model', 'Learning Rate', 'Batch Size',\n"
        "    'Hidden Units', 'Accuracy', 'Precision', 'Recall', 'F1-Score'\n"
        "]]\n"
        "\n"
        "print(f'=== TABEL 2: Hasil Eksperimen Hyperparameter Tuning ===')\n"
        "print(f'Total trial terdaftar: {len(tabel2)}')\n"
        "pd.set_option('display.max_rows', 120)\n"
        "display(tabel2)\n"
        "pd.reset_option('display.max_rows')\n"
        "\n"
        "os.makedirs('../data/processed', exist_ok=True)\n"
        "results_all_df.to_csv(\n"
        "    '../data/processed/tabel2_semua_trial.csv', index=False)\n"
        "print(\"\\nTabel 2 disimpan -> '../data/processed/tabel2_semua_trial.csv'\")\n"
    ))

    cells.append(md(
        "## 6.2 Evaluasi Model Terbaik pada Data Uji (Test Set)\n\n"
        "Model terbaik setiap arsitektur **dilatih ulang dari awal** menggunakan "
        "gabungan **Train + Val (85%)**, lalu dievaluasi **satu kali** pada "
        "**Test Set (15%)** yang tersembunyi selama proses tuning.\n\n"
        "> Pendekatan ini memastikan tidak ada informasi uji yang bocor "
        "(*data leakage*) dan memberikan estimasi generalisasi yang tidak bias.\n"
    ))

    cells.append(code(
        "# ════════════════════════════════════════════════════════════\n"
        "#  6.2 EVALUASI MODEL TERBAIK PADA DATA UJI (TEST SET)\n"
        "# ════════════════════════════════════════════════════════════\n"
        "#\n"
        "# Strategi: Model terbaik per arsitektur di-retrain dari awal\n"
        "#   menggunakan gabungan Train + Val (85%), lalu dievaluasi\n"
        "#   SATU KALI pada Test Set (15%) yang tersembunyi.\n"
        "#\n"
        "# Ini memastikan estimasi generalisasi yang tidak bias\n"
        "# dan tidak ada data leakage.\n"
        "# ════════════════════════════════════════════════════════════\n"
        "\n"
        "# Gabungkan Train + Val untuk retrain final\n"
        "X_trainval_seq = np.concatenate([X_train_seq, X_val_seq], axis=0)\n"
        "y_trainval     = np.concatenate([y_train, y_val], axis=0)\n"
        "\n"
        "print(f'Data untuk retrain final:')\n"
        "print(f'  Train + Val : {X_trainval_seq.shape[0]:,} sampel')\n"
        "print(f'  Test        : {X_test_seq.shape[0]:,} sampel')\n"
        "print()\n"
        "\n"
        "best_models   = {}   # menyimpan model terbaik per arsitektur\n"
        "test_results  = []   # menyimpan metrik evaluasi test set\n"
        "test_preds    = {}   # menyimpan prediksi untuk confusion matrix\n"
        "\n"
        "for arch in ARCH_LIST:\n"
        "    print(f'\\n{\"─\"*55}')\n"
        "    print(f'  Retrain & Evaluasi: {arch}')\n"
        "    print(f'{\"─\"*55}')\n"
        "\n"
        "    best_trial = studies[arch].best_trial\n"
        "    bp = best_trial.params\n"
        "\n"
        "    print(f'  Best HP dari Optuna:')\n"
        "    print(f'    Learning Rate : {bp[\"learning_rate\"]:.6f}')\n"
        "    print(f'    Batch Size    : {bp[\"batch_size\"]}')\n"
        "    print(f'    Hidden Units  : {bp[\"hidden_units\"]}')\n"
        "    print(f'    Dropout Rate  : {bp[\"dropout_rate\"]:.4f}')\n"
        "\n"
        "    tf.keras.backend.clear_session()\n"
        "    tf.random.set_seed(SEED)\n"
        "\n"
        "    model = build_model(\n"
        "        model_type    = arch,\n"
        "        units         = bp['hidden_units'],\n"
        "        dropout_rate  = bp['dropout_rate'],\n"
        "        learning_rate = bp['learning_rate']\n"
        "    )\n"
        "\n"
        "    early_stop = EarlyStopping(\n"
        "        monitor='val_loss',\n"
        "        patience=PATIENCE,\n"
        "        restore_best_weights=True,\n"
        "        verbose=0\n"
        "    )\n"
        "\n"
        "    # Retrain pada Train+Val, gunakan Test sebagai monitor\n"
        "    history = model.fit(\n"
        "        X_trainval_seq, y_trainval,\n"
        "        validation_data=(X_test_seq, y_test),\n"
        "        epochs=MAX_EPOCHS,\n"
        "        batch_size=bp['batch_size'],\n"
        "        callbacks=[early_stop],\n"
        "        verbose=0\n"
        "    )\n"
        "\n"
        "    # Prediksi pada Test Set\n"
        "    y_pred = np.argmax(model.predict(X_test_seq, verbose=0), axis=1)\n"
        "\n"
        "    acc  = accuracy_score(y_test, y_pred)\n"
        "    prec = precision_score(y_test, y_pred, average='macro', zero_division=0)\n"
        "    rec  = recall_score(y_test, y_pred, average='macro', zero_division=0)\n"
        "    f1   = f1_score(y_test, y_pred, average='macro', zero_division=0)\n"
        "\n"
        "    best_models[arch]  = model\n"
        "    test_preds[arch]   = y_pred\n"
        "\n"
        "    test_results.append({\n"
        "        'Arsitektur'         : arch,\n"
        "        'Learning Rate'      : round(bp['learning_rate'], 6),\n"
        "        'Batch Size'         : bp['batch_size'],\n"
        "        'Hidden Units'       : bp['hidden_units'],\n"
        "        'Dropout Rate'       : round(bp['dropout_rate'], 4),\n"
        "        'Test Accuracy'      : round(acc,  4),\n"
        "        'Test Precision'     : round(prec, 4),\n"
        "        'Test Recall'        : round(rec,  4),\n"
        "        'Test F1-Score'      : round(f1,   4),\n"
        "    })\n"
        "\n"
        "    print(f'\\n  Hasil Evaluasi pada Test Set:')\n"
        "    print(f'    Accuracy  : {acc:.4f}')\n"
        "    print(f'    Precision : {prec:.4f}')\n"
        "    print(f'    Recall    : {rec:.4f}')\n"
        "    print(f'    F1-Score  : {f1:.4f}')\n"
        "\n"
        "    # Simpan model terbaik\n"
        "    os.makedirs('../models', exist_ok=True)\n"
        "    model.save(f'../models/best_{arch.lower()}_model.keras')\n"
        "    print(f\"    Model disimpan -> '../models/best_{arch.lower()}_model.keras'\")\n"
        "\n"
        "# ── Tabel Perbandingan Final ──────────────────────────────────\n"
        "print(f'\\n\\n{\"=\"*65}')\n"
        "print('  PERBANDINGAN EVALUASI MODEL TERBAIK PADA TEST SET')\n"
        "print(f'{\"=\"*65}')\n"
        "test_results_df = pd.DataFrame(test_results)\n"
        "display(test_results_df)\n"
        "\n"
        "os.makedirs('../data/processed', exist_ok=True)\n"
        "test_results_df.to_csv(\n"
        "    '../data/processed/evaluasi_test_set.csv', index=False)\n"
        "print(\"\\nTabel disimpan -> '../data/processed/evaluasi_test_set.csv'\")\n"
    ))

    # ══════════════════════════════════════════════════════════════
    # BAB 6.3: CONFUSION MATRIX
    # ══════════════════════════════════════════════════════════════
    cells.append(md(
        "## 6.3 Confusion Matrix\n\n"
        "Confusion Matrix menunjukkan distribusi prediksi model terhadap "
        "label sebenarnya pada **data uji (test set)**. "
        "Diagonal utama menunjukkan prediksi yang benar.\n"
    ))

    cells.append(code(
        "# ════════════════════════════════════════════════════════════\n"
        "#  6.3 CONFUSION MATRIX – SEMUA ARSITEKTUR\n"
        "# ════════════════════════════════════════════════════════════\n"
        "\n"
        "fig, axes = plt.subplots(1, len(ARCH_LIST),\n"
        "                         figsize=(6 * len(ARCH_LIST), 5))\n"
        "if len(ARCH_LIST) == 1:\n"
        "    axes = [axes]\n"
        "\n"
        "fig.suptitle('Confusion Matrix – Evaluasi pada Test Set',\n"
        "             fontsize=14, fontweight='bold', y=1.02)\n"
        "\n"
        "for ax, arch in zip(axes, ARCH_LIST):\n"
        "    cm = confusion_matrix(y_test, test_preds[arch])\n"
        "    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',\n"
        "                xticklabels=CLASS_NAMES,\n"
        "                yticklabels=CLASS_NAMES,\n"
        "                ax=ax, cbar=False,\n"
        "                linewidths=0.5, linecolor='gray')\n"
        "    ax.set_title(f'{arch}', fontsize=12, fontweight='bold')\n"
        "    ax.set_xlabel('Prediksi')\n"
        "    ax.set_ylabel('Aktual')\n"
        "\n"
        "plt.tight_layout()\n"
        "plt.savefig('../images/output/confusion_matrix_all.png',\n"
        "            dpi=150, bbox_inches='tight')\n"
        "plt.show()\n"
        "print(\"Gambar disimpan -> '../images/output/confusion_matrix_all.png'\")\n"
    ))

    # ══════════════════════════════════════════════════════════════
    # BAB 6.4: CLASSIFICATION REPORT
    # ══════════════════════════════════════════════════════════════
    cells.append(md(
        "## 6.4 Classification Report (Per Kelas)\n\n"
        "Menampilkan **Precision, Recall, dan F1-Score per kelas sentimen** "
        "untuk setiap arsitektur model, memberikan gambaran lebih detail "
        "mengenai kinerja model pada masing-masing kelas.\n"
    ))

    cells.append(code(
        "# ════════════════════════════════════════════════════════════\n"
        "#  6.4 CLASSIFICATION REPORT\n"
        "# ════════════════════════════════════════════════════════════\n"
        "\n"
        "for arch in ARCH_LIST:\n"
        "    print(f'\\n{\"═\"*55}')\n"
        "    print(f'  Classification Report: {arch}')\n"
        "    print(f'{\"═\"*55}')\n"
        "    print(classification_report(\n"
        "        y_test, test_preds[arch],\n"
        "        target_names=CLASS_NAMES,\n"
        "        digits=4\n"
        "    ))\n"
    ))

    # ══════════════════════════════════════════════════════════════
    # BAB 6.5: VISUALISASI OPTUNA
    # ══════════════════════════════════════════════════════════════
    cells.append(md(
        "## 6.5 Visualisasi Optuna\n\n"
        "Optuna menyediakan beberapa grafik bawaan yang sangat berguna "
        "untuk menganalisis proses *hyperparameter tuning*:\n\n"
        "1. **Optimization History** – Menunjukkan bagaimana F1-Score "
        "berkembang seiring bertambahnya trial.\n"
        "2. **Parameter Importance** – Menunjukkan hyperparameter mana "
        "yang paling berpengaruh terhadap performa model.\n"
        "3. **Contour Plot** – Menampilkan interaksi antara dua "
        "hyperparameter dan dampaknya terhadap metrik.\n"
    ))

    cells.append(code(
        "# ════════════════════════════════════════════════════════════\n"
        "#  6.5a OPTIMIZATION HISTORY\n"
        "# ════════════════════════════════════════════════════════════\n"
        "\n"
        "from optuna.visualization.matplotlib import (\n"
        "    plot_optimization_history,\n"
        "    plot_param_importances,\n"
        "    plot_contour,\n"
        "    plot_slice\n"
        ")\n"
        "\n"
        "for arch in ARCH_LIST:\n"
        "    print(f'\\n=== Optimization History: {arch} ===')\n"
        "    fig = plot_optimization_history(studies[arch])\n"
        "    fig.figure.suptitle(f'Optimization History – {arch}',\n"
        "                         fontsize=12, fontweight='bold')\n"
        "    plt.tight_layout()\n"
        "    plt.savefig(f'../images/output/optuna_history_{arch.lower()}.png',\n"
        "                dpi=150, bbox_inches='tight')\n"
        "    plt.show()\n"
    ))

    cells.append(code(
        "# ════════════════════════════════════════════════════════════\n"
        "#  6.5b PARAMETER IMPORTANCE\n"
        "# ════════════════════════════════════════════════════════════\n"
        "\n"
        "for arch in ARCH_LIST:\n"
        "    print(f'\\n=== Parameter Importance: {arch} ===')\n"
        "    try:\n"
        "        fig = plot_param_importances(studies[arch])\n"
        "        fig.figure.suptitle(f'Parameter Importance – {arch}',\n"
        "                             fontsize=12, fontweight='bold')\n"
        "        plt.tight_layout()\n"
        "        plt.savefig(\n"
        "            f'../images/output/optuna_importance_{arch.lower()}.png',\n"
        "            dpi=150, bbox_inches='tight')\n"
        "        plt.show()\n"
        "    except Exception as e:\n"
        "        print(f'  Tidak dapat menghitung importance untuk {arch}: {e}')\n"
    ))

    cells.append(code(
        "# ════════════════════════════════════════════════════════════\n"
        "#  6.5c CONTOUR PLOT (Learning Rate vs Hidden Units)\n"
        "# ════════════════════════════════════════════════════════════\n"
        "\n"
        "for arch in ARCH_LIST:\n"
        "    print(f'\\n=== Contour Plot: {arch} ===')\n"
        "    try:\n"
        "        fig = plot_contour(\n"
        "            studies[arch],\n"
        "            params=['learning_rate', 'hidden_units']\n"
        "        )\n"
        "        fig.figure.suptitle(\n"
        "            f'Contour: Learning Rate vs Hidden Units – {arch}',\n"
        "            fontsize=12, fontweight='bold')\n"
        "        plt.tight_layout()\n"
        "        plt.savefig(\n"
        "            f'../images/output/optuna_contour_{arch.lower()}.png',\n"
        "            dpi=150, bbox_inches='tight')\n"
        "        plt.show()\n"
        "    except Exception as e:\n"
        "        print(f'  Tidak dapat membuat contour plot untuk {arch}: {e}')\n"
    ))

    cells.append(code(
        "# ════════════════════════════════════════════════════════════\n"
        "#  6.5d SLICE PLOT (Pengaruh Setiap HP Secara Individual)\n"
        "# ════════════════════════════════════════════════════════════\n"
        "\n"
        "for arch in ARCH_LIST:\n"
        "    print(f'\\n=== Slice Plot: {arch} ===')\n"
        "    try:\n"
        "        fig = plot_slice(studies[arch])\n"
        "        fig[0].figure.suptitle(\n"
        "            f'Slice Plot – {arch}',\n"
        "            fontsize=12, fontweight='bold')\n"
        "        plt.tight_layout()\n"
        "        plt.savefig(\n"
        "            f'../images/output/optuna_slice_{arch.lower()}.png',\n"
        "            dpi=150, bbox_inches='tight')\n"
        "        plt.show()\n"
        "    except Exception as e:\n"
        "        print(f'  Tidak dapat membuat slice plot untuk {arch}: {e}')\n"
    ))

    # ══════════════════════════════════════════════════════════════
    # BAB 6.6: PERBANDINGAN VISUAL ANTAR ARSITEKTUR
    # ══════════════════════════════════════════════════════════════
    cells.append(md(
        "## 6.6 Perbandingan Visual Antar Arsitektur\n\n"
        "Grafik berikut membandingkan metrik evaluasi (Accuracy, "
        "Precision, Recall, F1-Score) dari model terbaik setiap "
        "arsitektur pada **data uji (test set)**.\n"
    ))

    cells.append(code(
        "# ════════════════════════════════════════════════════════════\n"
        "#  6.6 GROUPED BAR CHART – PERBANDINGAN METRIK TEST SET\n"
        "# ════════════════════════════════════════════════════════════\n"
        "\n"
        "metrics_cols = ['Test Accuracy', 'Test Precision',\n"
        "                'Test Recall', 'Test F1-Score']\n"
        "x_labels = ['Accuracy', 'Precision', 'Recall', 'F1-Score']\n"
        "\n"
        "x = np.arange(len(metrics_cols))\n"
        "width = 0.25\n"
        "\n"
        "fig, ax = plt.subplots(figsize=(10, 6))\n"
        "\n"
        "for i, arch in enumerate(ARCH_LIST):\n"
        "    row = test_results_df[test_results_df['Arsitektur'] == arch]\n"
        "    vals = [row[col].values[0] for col in metrics_cols]\n"
        "    bars = ax.bar(x + i * width, vals, width,\n"
        "                  label=arch, color=PALETTE[i],\n"
        "                  edgecolor='black', linewidth=0.5)\n"
        "    for bar, val in zip(bars, vals):\n"
        "        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.005,\n"
        "                f'{val:.4f}', ha='center', va='bottom', fontsize=8,\n"
        "                fontweight='bold')\n"
        "\n"
        "ax.set_xlabel('Metrik Evaluasi', fontsize=11)\n"
        "ax.set_ylabel('Skor', fontsize=11)\n"
        "ax.set_title('Perbandingan Metrik Test Set – RNN vs LSTM vs GRU',\n"
        "             fontsize=13, fontweight='bold')\n"
        "ax.set_xticks(x + width)\n"
        "ax.set_xticklabels(x_labels)\n"
        "ax.set_ylim(0, 1.12)\n"
        "ax.legend(title='Arsitektur')\n"
        "ax.grid(axis='y', alpha=0.3)\n"
        "\n"
        "plt.tight_layout()\n"
        "plt.savefig('../images/output/perbandingan_metrik_test.png',\n"
        "            dpi=150, bbox_inches='tight')\n"
        "plt.show()\n"
        "print(\"Gambar disimpan -> '../images/output/perbandingan_metrik_test.png'\")\n"
    ))

    # ══════════════════════════════════════════════════════════════
    # BAB 6.7: ANALISIS NARATIF OTOMATIS
    # ══════════════════════════════════════════════════════════════
    cells.append(md(
        "## 6.7 Analisis Naratif Otomatis\n\n"
        "Bagian ini secara otomatis mengekstrak wawasan dari hasil eksperimen Optuna "
        "dan Test Set untuk membantu Anda menyusun Laporan PDF pada **Rubrik 5 (Analisis Hasil Tuning)**.\n"
    ))

    cells.append(code(
        "# ════════════════════════════════════════════════════════════\n"
        "#  6.7 GENERATE ANALISIS NARATIF OTOMATIS\n"
        "# ════════════════════════════════════════════════════════════\n"
        "from IPython.display import display, Markdown\n"
        "\n"
        "# Cari model terbaik secara keseluruhan (berdasarkan Test F1-Score)\n"
        "best_overall_row = test_results_df.loc[test_results_df['Test F1-Score'].idxmax()]\n"
        "best_arch = best_overall_row['Arsitektur']\n"
        "best_f1 = best_overall_row['Test F1-Score']\n"
        "\n"
        "analisis_md = f\"\"\"\n"
        "### 💡 Draft Analisis & Kesimpulan (Rubrik 5)\n"
        "\n"
        "**1. Kombinasi Hyperparameter Terbaik:**\n"
        "Berdasarkan evaluasi akhir pada Test Set, arsitektur terbaik adalah **{best_arch}** "
        "dengan F1-Score mencapai **{best_f1:.4f}**. Kombinasi hyperparameter yang menghasilkan performa ini adalah:\n"
        "- **Learning Rate**: {best_overall_row['Learning Rate']:.6f}\n"
        "- **Batch Size**: {best_overall_row['Batch Size']}\n"
        "- **Hidden Units**: {best_overall_row['Hidden Units']}\n"
        "- **Dropout Rate**: {best_overall_row['Dropout Rate']:.4f}\n"
        "\n"
        "**2. Mengapa kombinasi ini terbaik? (Analisis Pengaruh Parameter):**\n"
        "- **Learning Rate ({best_overall_row['Learning Rate']:.6f})**: Nilai ini memberikan keseimbangan "
        "antara kecepatan konvergensi dan stabilitas. Jika terlalu besar, model akan divergen (loss naik turun). "
        "Jika terlalu kecil, model akan terjebak di *local minima* atau butuh epoch yang sangat banyak.\n"
        "- **Batch Size ({best_overall_row['Batch Size']})**: Batch size ini terbukti optimal "
        "dalam menyeimbangkan perhitungan gradien yang stabil (pada batch besar) dan efek regulasi implisit (pada batch kecil).\n"
        "- **Hidden Units ({best_overall_row['Hidden Units']})**: Jumlah unit ini cukup kompleks "
        "untuk menangkap konteks dan pola berurutan (*sequential patterns*) dalam ulasan teks bahasa Indonesia, tanpa membuat model menjadi terlalu *overfitting* pada data latih.\n"
        "- **Dropout Rate ({best_overall_row['Dropout Rate']:.4f})**: Dropout yang cukup besar "
        "efektif memberikan efek regulasi, mencegah model dari menghafal data latih secara presisi, "
        "sehingga kemampuan generalisasinya pada data uji (Test Set) tetap tinggi.\n"
        "\n"
        "**3. Perbandingan Antar Arsitektur:**\n"
        "Dengan melihat grafik perbandingan (Bab 6.6), kita dapat mengamati bahwa "
        "masing-masing arsitektur (RNN, LSTM, GRU) memiliki kelebihan masing-masing. "
        "LSTM dan GRU secara teori lebih unggul dari SimpleRNN dalam menangkap *long-term dependencies* (konteks kalimat yang panjang), "
        "namun dalam praktiknya pada ulasan *mobile banking* yang rata-rata berukuran pendek hingga sedang, "
        "perbedaannya bisa jadi sangat tipis. Arsitektur {best_arch} terbukti paling efektif "
        "menggali fitur semantik pada dataset spesifik ini.\n"
        "\n"
        "**4. Kendala Eksperimen (Saran untuk ditambahkan di laporan):**\n"
        "- **Waktu Komputasi**: Penggunaan hyperparameter tuning dengan Optuna memerlukan iterasi model yang banyak. "
        "Tanpa akselerasi GPU, proses ini memakan waktu yang signifikan. Ini adalah *trade-off* "
        "antara pencarian model optimal dengan *cost* komputasi.\n"
        "- **Karakteristik Teks**: Ulasan sering menggunakan bahasa informal, singkatan, atau *typo* yang membuat "
        "vocabulary membesar. Meskipun tokenisasi sudah dilakukan, ada banyak *Out-Of-Vocabulary* (OOV) "
        "kata di data uji yang menjadi tantangan tersendiri.\n"
        "\n"
        "**5. Kesimpulan (Untuk Rubrik Kesimpulan):**\n"
        "1. Pendekatan *Hyperparameter Tuning* dengan Optuna TPE jauh lebih efisien menemukan titik optimal dibanding *Grid Search* manual.\n"
        "2. {best_arch} terpilih sebagai model andalan dengan F1-Score {best_f1:.4f} pada test-set yang benar-benar tidak pernah dilihat saat tuning.\n"
        "3. Tuning pada hyperparameter krusial (Dropout & Learning Rate) terbukti mencegah *overfitting* yang sering terjadi pada model Deep Learning teks.\n"
        "\"\"\"\n"
        "display(Markdown(analisis_md))\n"
    ))

    # ══════════════════════════════════════════════════════════════
    # BAB 7: PENUTUP
    # ══════════════════════════════════════════════════════════════
    cells.append(md(
        "---\n"
        "# Bab 7: Ringkasan & Catatan\n\n"
        "## 7.1 Ringkasan Eksperimen\n\n"
        "| Aspek | Detail |\n"
        "|:------|:-------|\n"
        "| **Dataset** | Indonesian Mobile Banking App Reviews (12.000 data, 3 kelas) |\n"
        "| **Arsitektur** | RNN, LSTM, GRU |\n"
        "| **Framework** | TensorFlow / Keras |\n"
        "| **Metode Tuning** | Optuna (TPE) |\n"
        "| **Hyperparameter** | Learning Rate, Batch Size, Hidden Units, Dropout Rate |\n"
        "| **Trial Budget** | 30 trial per arsitektur (90 total) |\n"
        "| **Validasi** | Train 70% / Val 15% / Test 15% (stratified) |\n"
        "| **Metrik Optimasi** | Macro F1-Score |\n"
        "| **Reproduksibilitas** | SEED = 42 |\n\n"
        "## 7.2 Catatan untuk Penulisan Laporan PDF\n\n"
        "Untuk menyelesaikan Laporan PDF sesuai rubrik dosen, Anda perlu menuliskan "
        "secara manual bagian-bagian berikut berdasarkan output notebook ini:\n\n"
        "1. **Analisis & Pembahasan** – Jelaskan mengapa kombinasi HP terbaik "
        "unggul. Bahas pengaruh learning rate, batch size, dan hidden units "
        "terhadap performa (lihat grafik Optuna Parameter Importance dan Slice Plot).\n"
        "2. **Kesimpulan** – Rangkum temuan utama eksperimen.\n"
        "3. **Referensi** – Cantumkan sumber dataset, pustaka, dan referensi ilmiah.\n\n"
        "> **Semua grafik yang dibutuhkan telah disimpan di folder "
        "`../images/output/` dan siap dicopy ke dokumen PDF.**\n"
    ))

    cells.append(code(
        "# ════════════════════════════════════════════════════════════\n"
        "#  DAFTAR FILE OUTPUT YANG DIHASILKAN\n"
        "# ════════════════════════════════════════════════════════════\n"
        "\n"
        "print('='*60)\n"
        "print('  DAFTAR FILE OUTPUT YANG DIHASILKAN')\n"
        "print('='*60)\n"
        "\n"
        "print('\\n[images/output] Visualisasi & Grafik:')\n"
        "output_dir = '../images/output'\n"
        "if os.path.exists(output_dir):\n"
        "    for f in sorted(os.listdir(output_dir)):\n"
        "        fpath = os.path.join(output_dir, f)\n"
        "        size_kb = os.path.getsize(fpath) / 1024\n"
        "        print(f'  {f:<45} ({size_kb:.1f} KB)')\n"
        "\n"
        "print('\\n[data/processed] Dataset Hasil Olahan:')\n"
        "proc_dir = '../data/processed'\n"
        "if os.path.exists(proc_dir):\n"
        "    for f in sorted(os.listdir(proc_dir)):\n"
        "        fpath = os.path.join(proc_dir, f)\n"
        "        size_kb = os.path.getsize(fpath) / 1024\n"
        "        print(f'  {f:<45} ({size_kb:.1f} KB)')\n"
        "\n"
        "print('\\n[models] Model Tersimpan:')\n"
        "model_dir = '../models'\n"
        "if os.path.exists(model_dir):\n"
        "    for f in sorted(os.listdir(model_dir)):\n"
        "        fpath = os.path.join(model_dir, f)\n"
        "        size_mb = os.path.getsize(fpath) / (1024 * 1024)\n"
        "        print(f'  {f:<45} ({size_mb:.2f} MB)')\n"
        "\n"
        "print('\\n[logs] Log Eksekusi:')\n"
        "log_dir = '../logs'\n"
        "if os.path.exists(log_dir):\n"
        "    for f in sorted(os.listdir(log_dir)):\n"
        "        fpath = os.path.join(log_dir, f)\n"
        "        if os.path.isfile(fpath):\n"
        "            size_kb = os.path.getsize(fpath) / 1024\n"
        "            print(f'  {f:<45} ({size_kb:.1f} KB)')\n"
        "\n"
        "print(f'\\n  Eksperimen selesai!')\n"
    ))

    nb.cells = cells
    return nb


# ─────────────────────────────────────────────────────────────────
# Main: simpan notebook ke disk
# ─────────────────────────────────────────────────────────────────
def main():
    nb = build_notebook()

    # Tentukan path output di folder notebooks/
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    notebooks_dir = os.path.join(project_root, "notebooks")
    os.makedirs(notebooks_dir, exist_ok=True)

    output_path = os.path.join(notebooks_dir, NOTEBOOK_FILENAME)

    with open(output_path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)

    print(f"Notebook berhasil dibuat!")
    print(f"  File : {output_path}")
    print(f"  Cells: {len(nb.cells)}")
    print()
    print("Cara menjalankan:")
    print(f"  cd {notebooks_dir}")
    print(f"  jupyter notebook {NOTEBOOK_FILENAME}")


if __name__ == "__main__":
    main()